<?php
/**
 * MlsOfficeStats
 *
 * PHP version 5
 *
 * @category Class
 * @package  Redwood
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Redwood API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Redwood\Models;

use \ArrayAccess;
use \Redwood\ObjectSerializer;

/**
 * MlsOfficeStats Class Doc Comment
 *
 * @category Class
 * @package  Redwood
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MlsOfficeStats implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MlsOfficeStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'stat_sales_ltm' => 'int',
'_353903392' => 'int',
'stat_agent_count' => 'int',
'stat_real_satisfied_rating' => 'float'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'stat_sales_ltm' => null,
'_353903392' => null,
'stat_agent_count' => null,
'stat_real_satisfied_rating' => 'float'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'stat_sales_ltm' => 'stat_sales_ltm',
'_353903392' => '353903392',
'stat_agent_count' => 'stat_agent_count',
'stat_real_satisfied_rating' => 'stat_real_satisfied_rating'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'stat_sales_ltm' => 'setStatSalesLtm',
'_353903392' => 'set353903392',
'stat_agent_count' => 'setStatAgentCount',
'stat_real_satisfied_rating' => 'setStatRealSatisfiedRating'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'stat_sales_ltm' => 'getStatSalesLtm',
'_353903392' => 'get353903392',
'stat_agent_count' => 'getStatAgentCount',
'stat_real_satisfied_rating' => 'getStatRealSatisfiedRating'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['stat_sales_ltm'] = isset($data['stat_sales_ltm']) ? $data['stat_sales_ltm'] : null;
        $this->container['_353903392'] = isset($data['_353903392']) ? $data['_353903392'] : null;
        $this->container['stat_agent_count'] = isset($data['stat_agent_count']) ? $data['stat_agent_count'] : null;
        $this->container['stat_real_satisfied_rating'] = isset($data['stat_real_satisfied_rating']) ? $data['stat_real_satisfied_rating'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets stat_sales_ltm
     *
     * @return int
     */
    public function getStatSalesLtm()
    {
        return $this->container['stat_sales_ltm'];
    }

    /**
     * Sets stat_sales_ltm
     *
     * @param int $stat_sales_ltm stat_sales_ltm
     *
     * @return $this
     */
    public function setStatSalesLtm($stat_sales_ltm)
    {
        $this->container['stat_sales_ltm'] = $stat_sales_ltm;

        return $this;
    }

    /**
     * Gets _353903392
     *
     * @return int
     */
    public function get353903392()
    {
        return $this->container['_353903392'];
    }

    /**
     * Sets _353903392
     *
     * @param int $_353903392 _353903392
     *
     * @return $this
     */
    public function set353903392($_353903392)
    {
        $this->container['_353903392'] = $_353903392;

        return $this;
    }

    /**
     * Gets stat_agent_count
     *
     * @return int
     */
    public function getStatAgentCount()
    {
        return $this->container['stat_agent_count'];
    }

    /**
     * Sets stat_agent_count
     *
     * @param int $stat_agent_count stat_agent_count
     *
     * @return $this
     */
    public function setStatAgentCount($stat_agent_count)
    {
        $this->container['stat_agent_count'] = $stat_agent_count;

        return $this;
    }

    /**
     * Gets stat_real_satisfied_rating
     *
     * @return float
     */
    public function getStatRealSatisfiedRating()
    {
        return $this->container['stat_real_satisfied_rating'];
    }

    /**
     * Sets stat_real_satisfied_rating
     *
     * @param float $stat_real_satisfied_rating stat_real_satisfied_rating
     *
     * @return $this
     */
    public function setStatRealSatisfiedRating($stat_real_satisfied_rating)
    {
        $this->container['stat_real_satisfied_rating'] = $stat_real_satisfied_rating;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
